apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth  # Must be named aws-auth
  namespace: kube-system # Must be in the kube-system namespace
data:
  mapUsers: |
    - userarn: "arn:aws:iam::${AWS_ACCOUNT_ID}:user/${IAM_USERNAME}"
      username: "${IAM_USERNAME}"   # Must match your IAM username
      groups:
        - system:masters  # Gives admin access to cluster