apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-dev-eks-deployment
  namespace: nest-dev-eks-namespace  # Must match Service namespace: nest-dev-eks-namespace
  labels:
    app: nest-app     # Must match Service selector: app: nest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-app   # Must match Service selector: app: nest-app
  template:
    metadata:
      labels:
        app: nest-app # Must match Service selector: app: nest-app
    spec:
      serviceAccountName: nest-dev-eks-service-account
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: nest-dev-eks-secret-provider-class # Must match SecretProviderClass metadata.name: "nest-dev-eks-secrets"
      containers:
      - name: nest-dev-eks-container
        image: 651783246143.dkr.ecr.us-east-1.amazonaws.com/nest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # Should align with Service port 80 for proper traffic routing
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true