apiVersion: apps/v1
kind: Deployment
metadata:
  name: "${APP_NAME}-deployment"
  namespace: "${NAMESPACE}" # Must match Service namespace
  labels:
    app: "${APP_NAME}" # Must match Service selector
spec:
  replicas: "${REPLICAS}"
  selector:
    matchLabels:
      app: "${APP_NAME}" # Must match Service selector
  template:
    metadata:
      labels:
        app: "${APP_NAME}" # Must match Service selector
    spec:
      serviceAccountName: "${APP_NAME}-service-account"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "${APP_SECRETS}" # Must match SecretProviderClass metadata name
      containers:
      - name: "${APP_NAME}-container"
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}"
        imagePullPolicy: Always
        ports:
        - containerPort: "${PORT}" # Must match Service port
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true