apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secretsmanager  # Must match Deployment volumeAttributes.secretProviderClass: "aws-secretsmanager"
  namespace: nest-app  # Must match Deployment and Service namespace: nest-app
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:651783246143:secret:app-secrets-ATCH9v"
          objectAlias: "app-secrets"