apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nest-dev-eks-secret-provider-class  # Must match Deployment volumeAttributes.secretProviderClass: "nest-dev-eks-secrets"
  namespace: nest-dev-eks-namespace  # Must match Deployment and Service namespace: nest-dev-eks-namespace
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:651783246143:secret:app-secrets-ATCH9v"
          objectAlias: "nest-dev-eks-secrets"