# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: aws-secretsmanager  # Must match Deployment volumeAttributes.secretProviderClass: "aws-secretsmanager"
#   namespace: nest-app  # Must match Deployment and Service namespace: nest-app
# spec:
#   provider: aws
#   parameters:
#     objects: |
#         - objectName: "arn:aws:secretsmanager:us-east-1:651783246143:secret:app-secrets-ATCH9v"
#           objectAlias: "app-secrets"

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "${APP_SECRETS}" # Must match Deployment volumeAttributes.secretProviderClass
  namespace: "${NAMESPACE}" # Must match Deployment and Service namespace
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:${REGION}:${AWS_ACCOUNT_ID}:secret:${SECRET_NAME}-${SECRET_SUFFIX}"
          objectAlias: "${SECRET_ALIAS}"