# apiVersion: v1
# kind: Service
# metadata:
#   name: nest-app  
#   namespace: nest-app  # Must match Deployment namespace: nest-app
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
#     service.beta.kubernetes.io/aws-load-balancer-internal: "false"
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
# spec:
#   type: LoadBalancer
#   ports:
#     - name: web
#       port: 80  # Must match Deployment containerPort: 80
#   selector:
#     app: nest-app  # Must match Deployment labels: app: nest-app


apiVersion: v1
kind: Service
metadata:
  name: "${APP_NAME}-service"
  namespace: "${NAMESPACE}" # Must match Deployment namespace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "${LB_INTERNAL}"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "${CROSS_ZONE_ENABLED}"
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: "${PORT}" # Must match Deployment containerPort
  selector:
    app: "${APP_NAME}" # Must match Deployment labels: app