# rds variables
variable "project_name" {}
variable "environment" {}
variable "private_data_subnet_az1_id" {}
variable "private_data_subnet_az2_id" {}
variable "engine" {}
variable "engine_version" {}
variable "multi_az_deployment" {}
variable "database_instance_identifier" {}
variable "rds_db_username" {}
variable "rds_db_password" {}
variable "rds_db_name" {}
variable "database_instance_class" {}
variable "allocated_storage" {}
variable "database_security_group_id" {}
variable "availability_zone_1" {}
variable "skip_final_snapshot" {}
variable "publicly_accessible" {}